### PR TITLE
I don't know what to say here... more radios...

### PR DESCRIPTION
**Pull request by Xastreh**

### CODE REVIEW

**Comment by Xastreh** [comment]
I was going to add The Beach, but it had a token. ¯\_(ツ)_/¯

**Comment by zeyla** [comment]
We currently can't support authenticated radios (including tokenized ones), so I've removed The Beach.

**Comment by Xastreh** [comment]
Hm ok. I was told to add it. But I had tested it on the bot and it didn’t worked which is the thing that pissed me off. 😫

**Comment by Xastreh** [comment]
I meant to say that there was a token and I didn’t want to add it. It worked, but yeah...
Ok, thanks anyways.

**Pull request merged**
