### PR TITLE
Fix playlist loading

### PR DESCRIPTION
**Pull request by MartinItsLinda**
Playlists wouldn't load as AudioPlaylist#getSelectedTrack would return the first track in a playlist, preventing the rest of the tracks getting loaded

### CODE REVIEW

**Comment by ducc** [comment]
This is by design. Most users just want a single song to be played.

**Comment by MartinItsLinda** [comment]
What about using a flag? For those that actually want to load the full playlist

**Comment by ducc** [comment]
Any user that actually understands how flags work knows they just need to go to the playlist page.

**Comment by MartinItsLinda** [comment]
Fair enough

**Pull request closed without merging**
