### PR TITLE
A radio a day keeps the ducc away

### PR DESCRIPTION
**Pull request by Xastreh**
quacc

### CODE REVIEW

**Comment by Dot-Rar** [comment]
My nibba u need to add a space between "Radio" and "Romania"

**Comment by Xastreh** [comment]
Opps. I’ll fix it. Thanks for pointing that out. I was in a rush when I was adding that radio.

**Comment by Xastreh** [comment]
I can’t fix it right now since I’m on my phone. I’ll be back on my computer on Sunday. But anyways, I’ve tryed fixing it but it just won’t allow me to submit the pull request. Rip rip rip.... 😞

**Comment by zeyla** [comment]
Thanks

**Comment by Xastreh** [comment]
Oh, thanks zeyla

**Pull request merged**
