### PR TITLE
!!!shard yes haha!!

### PR DESCRIPTION
**Pull request by Dot-Rar**

### CODE REVIEW

**Comment by ducc** [comment]
```java
ShardInfo shardInfo = context.getEvent().getJDA().getShardInfo();
```
...

**Comment by Dot-Rar** [comment]
DabRar | Son to John - Today at 19:03
henlo i would like to order a suicide

**Comment by ducc** [comment]
ok jus remove ur changes from MusicBot.java too and maybe use a variable for event :)

**Comment by Dot-Rar** [comment]
ok if i can have an suicide with that

**Comment by ducc** [comment]
sure

**Comment by Dot-Rar** [comment]
thank, 1 commit coming right up

**Comment by ducc** [comment]
use `context.reply` for consistency

**Comment by Dot-Rar** [comment]
woa ducc has all the tricks!!

**Comment by ducc** [comment]
what about the String.format thats part of context.reply .. :)

**Comment by ducc** [comment]
fine.... ill do it for you

**Pull request merged**
